title: Paweł Aksman # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a graduate of the University of Silesia in Cieszyn, specializing in organ performance at the Faculty of Arts 🎹. Currently, I am embarking on my journey as a software tester. In pursuit of this goal, I actively explore various materials to expand my knowledge necessary in this field 💪. My particular interests revolve around test automation, which is why I am learning programming languages and tools dedicated to test automation. Among my achievements is winning a competition for the best test plan organized by testerzy.pl 🥇. I also hold the MITC Software Testing Level 01 certificate 💪. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
